/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package notifications_pkg

import "pronimbusapi_lib/configuration_pkg"
import "pronimbusapi_lib/models_pkg"

/*
 * Interface for the NOTIFICATIONS_IMPL
 */
type NOTIFICATIONS interface {
    CreateFetchInfoAboutEmailNotificationsSentOnBehalfOfAClient (*models_pkg.GetNotificationsRequest) (*models_pkg.GetNotificationsResponse, error)
}

/*
 * Factory for the NOTIFICATIONS interaface returning NOTIFICATIONS_IMPL
 */
func NewNOTIFICATIONS(config configuration_pkg.CONFIGURATION) *NOTIFICATIONS_IMPL {
    client := new(NOTIFICATIONS_IMPL)
    client.config = config
    return client
}