/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard.Http.Client;

using ProNimbusAPI.Standard.Models;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Exceptions
{
    public class ProductDetailsErrorResponseException : APIException 
    {
        // These fields hold the values for the public properties.
        private double? code;
        private string message;
        private object result;
        private object errors;

        /// <summary>
        /// A numeric representation of the status of the call. Values possible in a unsuccessful response are
        ///   * `1` - Unknown error in the ProNimbus code
        ///   * `3` - No matching products were found
        ///   * `4` - clientCode does not exist
        /// </summary>
        [JsonProperty("code")]
        public double? Code 
        { 
            get 
            {
                return this.code; 
            } 
            private set 
            {
                this.code = value;
            }
        }

        /// <summary>
        /// A string representation of the status of the call. Values possible in a unsuccessful response are
        ///   * Unknown error: *error message*
        ///   * No matching products were found
        ///   * clientCode='*clientCode*' does not exist
        /// </summary>
        [JsonProperty("message")]
        public string Message 
        { 
            get 
            {
                return this.message; 
            } 
            private set 
            {
                this.message = value;
            }
        }

        /// <summary>
        /// An empty object. No results are returned as part of a status 400 result.
        /// </summary>
        [JsonProperty("result")]
        public object Result 
        { 
            get 
            {
                return this.result; 
            } 
            private set 
            {
                this.result = value;
            }
        }

        /// <summary>
        /// An object describing the fields in the request that are in error. May contain multiple levels if the fields in error are part of a field that is an object. If there is no error this object is empty.
        /// </summary>
        [JsonProperty("errors")]
        public object Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            private set 
            {
                this.errors = value;
            }
        }

        /// <summary>
        /// Initialization constructor
        /// </summary>
        /// <param name="reason"> The reason for throwing exception </param>
        /// <param name="context"> The HTTP context that encapsulates request and response objects </param>
        public ProductDetailsErrorResponseException(string reason, HttpContext context)
            : base(reason, context)
        {
        }
    }
} 