/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for BackorderWarningEnum enum
 */
type BackorderWarningEnum int

/**
 * Value collection for BackorderWarningEnum enum
 */
const (
    BackorderWarning_Y BackorderWarningEnum = 1 + iota
    BackorderWarning_N
)

func (r BackorderWarningEnum) MarshalJSON() ([]byte, error) { 
    s := BackorderWarningEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *BackorderWarningEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  BackorderWarningEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts BackorderWarningEnum to its string representation
 */
func BackorderWarningEnumToValue(backorderWarningEnum BackorderWarningEnum) string {
    switch backorderWarningEnum {
        case BackorderWarning_Y:
    		return "Y"		
        case BackorderWarning_N:
    		return "N"		
        default:
        	return "Y"
    }
}

/**
 * Converts BackorderWarningEnum Array to its string Array representation
*/
func BackorderWarningEnumArrayToValue(backorderWarningEnum []BackorderWarningEnum) []string {
    convArray := make([]string,len( backorderWarningEnum))
    for i:=0; i<len(backorderWarningEnum);i++ {
        convArray[i] = BackorderWarningEnumToValue(backorderWarningEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func BackorderWarningEnumFromValue(value string) BackorderWarningEnum {
    switch value {
        case "Y":
            return BackorderWarning_Y
        case "N":
            return BackorderWarning_N
        default:
            return BackorderWarning_Y
    }
}
