/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for DetailView1Enum enum
 */
type DetailView1Enum int

/**
 * Value collection for DetailView1Enum enum
 */
const (
    DetailView1_FALSE DetailView1Enum = 1 + iota
    DetailView1_TRUE
)

func (r DetailView1Enum) MarshalJSON() ([]byte, error) { 
    s := DetailView1EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *DetailView1Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  DetailView1EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts DetailView1Enum to its string representation
 */
func DetailView1EnumToValue(detailView1Enum DetailView1Enum) string {
    switch detailView1Enum {
        case DetailView1_FALSE:
    		return "false"		
        case DetailView1_TRUE:
    		return "true"		
        default:
        	return "false"
    }
}

/**
 * Converts DetailView1Enum Array to its string Array representation
*/
func DetailView1EnumArrayToValue(detailView1Enum []DetailView1Enum) []string {
    convArray := make([]string,len( detailView1Enum))
    for i:=0; i<len(detailView1Enum);i++ {
        convArray[i] = DetailView1EnumToValue(detailView1Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func DetailView1EnumFromValue(value string) DetailView1Enum {
    switch value {
        case "false":
            return DetailView1_FALSE
        case "true":
            return DetailView1_TRUE
        default:
            return DetailView1_FALSE
    }
}
