/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for DetailViewEnum enum
 */
type DetailViewEnum int

/**
 * Value collection for DetailViewEnum enum
 */
const (
    DetailView_ENUM_0 DetailViewEnum = 0
    DetailView_ENUM_1 = 1
)

func (r DetailViewEnum) MarshalJSON() ([]byte, error) { 
    s := DetailViewEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *DetailViewEnum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  DetailViewEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts DetailViewEnum to its int representation
 */
func DetailViewEnumToValue(detailViewEnum DetailViewEnum) int {
    switch detailViewEnum {
        case DetailView_ENUM_0:
    		return 0		
        case DetailView_ENUM_1:
    		return 1		
        default:
        	return 0
    }
}

/**
 * Converts DetailViewEnum Array to its string Array representation
*/
func DetailViewEnumArrayToValue(detailViewEnum []DetailViewEnum) []int {
    convArray := make([]int,len( detailViewEnum))
    for i:=0; i<len(detailViewEnum);i++ {
        convArray[i] = DetailViewEnumToValue(detailViewEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func DetailViewEnumFromValue(value int) DetailViewEnum {
    switch value {
        case 0:
            return DetailView_ENUM_0
        case 1:
            return DetailView_ENUM_1
        default:
            return DetailView_ENUM_0
    }
}
