/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for FoodPerishableEnum enum
 */
type FoodPerishableEnum int

/**
 * Value collection for FoodPerishableEnum enum
 */
const (
    FoodPerishable_Y FoodPerishableEnum = 1 + iota
    FoodPerishable_N
)

func (r FoodPerishableEnum) MarshalJSON() ([]byte, error) { 
    s := FoodPerishableEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *FoodPerishableEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  FoodPerishableEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts FoodPerishableEnum to its string representation
 */
func FoodPerishableEnumToValue(foodPerishableEnum FoodPerishableEnum) string {
    switch foodPerishableEnum {
        case FoodPerishable_Y:
    		return "Y"		
        case FoodPerishable_N:
    		return "N"		
        default:
        	return "Y"
    }
}

/**
 * Converts FoodPerishableEnum Array to its string Array representation
*/
func FoodPerishableEnumArrayToValue(foodPerishableEnum []FoodPerishableEnum) []string {
    convArray := make([]string,len( foodPerishableEnum))
    for i:=0; i<len(foodPerishableEnum);i++ {
        convArray[i] = FoodPerishableEnumToValue(foodPerishableEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func FoodPerishableEnumFromValue(value string) FoodPerishableEnum {
    switch value {
        case "Y":
            return FoodPerishable_Y
        case "N":
            return FoodPerishable_N
        default:
            return FoodPerishable_Y
    }
}
