/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for OnHoldEnum enum
 */
type OnHoldEnum int

/**
 * Value collection for OnHoldEnum enum
 */
const (
    OnHold_ENUM_0 OnHoldEnum = 0
    OnHold_ENUM_1 = 1
)

func (r OnHoldEnum) MarshalJSON() ([]byte, error) { 
    s := OnHoldEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *OnHoldEnum) UnmarshalJSON(data []byte) error { 
    var s int 
    json.Unmarshal(data, &s)
    v :=  OnHoldEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts OnHoldEnum to its int representation
 */
func OnHoldEnumToValue(onHoldEnum OnHoldEnum) int {
    switch onHoldEnum {
        case OnHold_ENUM_0:
    		return 0		
        case OnHold_ENUM_1:
    		return 1		
        default:
        	return 0
    }
}

/**
 * Converts OnHoldEnum Array to its string Array representation
*/
func OnHoldEnumArrayToValue(onHoldEnum []OnHoldEnum) []int {
    convArray := make([]int,len( onHoldEnum))
    for i:=0; i<len(onHoldEnum);i++ {
        convArray[i] = OnHoldEnumToValue(onHoldEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func OnHoldEnumFromValue(value int) OnHoldEnum {
    switch value {
        case 0:
            return OnHold_ENUM_0
        case 1:
            return OnHold_ENUM_1
        default:
            return OnHold_ENUM_0
    }
}
