/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for RequestTypeEnum enum
 */
type RequestTypeEnum int

/**
 * Value collection for RequestTypeEnum enum
 */
const (
    RequestType_PROCESSED RequestTypeEnum = 1 + iota
    RequestType_SHIPPED
    RequestType_EXCEPTION
    RequestType_RETURNED
    RequestType_ENUM_DELIVERY_ATTEMPT
    RequestType_ENUM_OUT_FOR_DELIVERY
    RequestType_DELIVERED
)

func (r RequestTypeEnum) MarshalJSON() ([]byte, error) { 
    s := RequestTypeEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *RequestTypeEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  RequestTypeEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts RequestTypeEnum to its string representation
 */
func RequestTypeEnumToValue(requestTypeEnum RequestTypeEnum) string {
    switch requestTypeEnum {
        case RequestType_PROCESSED:
    		return "Processed"		
        case RequestType_SHIPPED:
    		return "Shipped"		
        case RequestType_EXCEPTION:
    		return "Exception"		
        case RequestType_RETURNED:
    		return "Returned"		
        case RequestType_ENUM_DELIVERY_ATTEMPT:
    		return "Enum_Delivery Attempt"		
        case RequestType_ENUM_OUT_FOR_DELIVERY:
    		return "Enum_Out for Delivery"		
        case RequestType_DELIVERED:
    		return "Delivered"		
        default:
        	return "Processed"
    }
}

/**
 * Converts RequestTypeEnum Array to its string Array representation
*/
func RequestTypeEnumArrayToValue(requestTypeEnum []RequestTypeEnum) []string {
    convArray := make([]string,len( requestTypeEnum))
    for i:=0; i<len(requestTypeEnum);i++ {
        convArray[i] = RequestTypeEnumToValue(requestTypeEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func RequestTypeEnumFromValue(value string) RequestTypeEnum {
    switch value {
        case "Processed":
            return RequestType_PROCESSED
        case "Shipped":
            return RequestType_SHIPPED
        case "Exception":
            return RequestType_EXCEPTION
        case "Returned":
            return RequestType_RETURNED
        case "Enum_Delivery_Attempt":
            return RequestType_ENUM_DELIVERY_ATTEMPT
        case "Enum_Out_for_Delivery":
            return RequestType_ENUM_OUT_FOR_DELIVERY
        case "Delivered":
            return RequestType_DELIVERED
        default:
            return RequestType_PROCESSED
    }
}
