/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Status4Enum enum
 */
type Status4Enum int

/**
 * Value collection for Status4Enum enum
 */
const (
    Status4_SUCCESS Status4Enum = 1 + iota
    Status4_FAILURE
)

func (r Status4Enum) MarshalJSON() ([]byte, error) { 
    s := Status4EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Status4Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Status4EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Status4Enum to its string representation
 */
func Status4EnumToValue(status4Enum Status4Enum) string {
    switch status4Enum {
        case Status4_SUCCESS:
    		return "success"		
        case Status4_FAILURE:
    		return "failure"		
        default:
        	return "success"
    }
}

/**
 * Converts Status4Enum Array to its string Array representation
*/
func Status4EnumArrayToValue(status4Enum []Status4Enum) []string {
    convArray := make([]string,len( status4Enum))
    for i:=0; i<len(status4Enum);i++ {
        convArray[i] = Status4EnumToValue(status4Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Status4EnumFromValue(value string) Status4Enum {
    switch value {
        case "success":
            return Status4_SUCCESS
        case "failure":
            return Status4_FAILURE
        default:
            return Status4_SUCCESS
    }
}
