/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Status2Enum enum
 */
type Status2Enum int

/**
 * Value collection for Status2Enum enum
 */
const (
    Status2_FAILURE Status2Enum = 1 + iota
    Status2_SUCCESS
)

func (r Status2Enum) MarshalJSON() ([]byte, error) { 
    s := Status2EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Status2Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Status2EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Status2Enum to its string representation
 */
func Status2EnumToValue(status2Enum Status2Enum) string {
    switch status2Enum {
        case Status2_FAILURE:
    		return "failure"		
        case Status2_SUCCESS:
    		return "success"		
        default:
        	return "failure"
    }
}

/**
 * Converts Status2Enum Array to its string Array representation
*/
func Status2EnumArrayToValue(status2Enum []Status2Enum) []string {
    convArray := make([]string,len( status2Enum))
    for i:=0; i<len(status2Enum);i++ {
        convArray[i] = Status2EnumToValue(status2Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Status2EnumFromValue(value string) Status2Enum {
    switch value {
        case "failure":
            return Status2_FAILURE
        case "success":
            return Status2_SUCCESS
        default:
            return Status2_FAILURE
    }
}
