/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Status3Enum enum
 */
type Status3Enum int

/**
 * Value collection for Status3Enum enum
 */
const (
    Status3_SUCCESS Status3Enum = 1 + iota
    Status3_FAILURE
)

func (r Status3Enum) MarshalJSON() ([]byte, error) { 
    s := Status3EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Status3Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Status3EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Status3Enum to its string representation
 */
func Status3EnumToValue(status3Enum Status3Enum) string {
    switch status3Enum {
        case Status3_SUCCESS:
    		return "success"		
        case Status3_FAILURE:
    		return "failure"		
        default:
        	return "success"
    }
}

/**
 * Converts Status3Enum Array to its string Array representation
*/
func Status3EnumArrayToValue(status3Enum []Status3Enum) []string {
    convArray := make([]string,len( status3Enum))
    for i:=0; i<len(status3Enum);i++ {
        convArray[i] = Status3EnumToValue(status3Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Status3EnumFromValue(value string) Status3Enum {
    switch value {
        case "success":
            return Status3_SUCCESS
        case "failure":
            return Status3_FAILURE
        default:
            return Status3_SUCCESS
    }
}
