/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Type8Enum enum
 */
type Type8Enum int

/**
 * Value collection for Type8Enum enum
 */
const (
    Type8_REGULAR Type8Enum = 1 + iota
    Type8_RETURN
)

func (r Type8Enum) MarshalJSON() ([]byte, error) { 
    s := Type8EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Type8Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Type8EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Type8Enum to its string representation
 */
func Type8EnumToValue(type8Enum Type8Enum) string {
    switch type8Enum {
        case Type8_REGULAR:
    		return "REGULAR"		
        case Type8_RETURN:
    		return "RETURN"		
        default:
        	return "REGULAR"
    }
}

/**
 * Converts Type8Enum Array to its string Array representation
*/
func Type8EnumArrayToValue(type8Enum []Type8Enum) []string {
    convArray := make([]string,len( type8Enum))
    for i:=0; i<len(type8Enum);i++ {
        convArray[i] = Type8EnumToValue(type8Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Type8EnumFromValue(value string) Type8Enum {
    switch value {
        case "REGULAR":
            return Type8_REGULAR
        case "RETURN":
            return Type8_RETURN
        default:
            return Type8_REGULAR
    }
}
