/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Units3Enum enum
 */
type Units3Enum int

/**
 * Value collection for Units3Enum enum
 */
const (
    Units3_MI Units3Enum = 1 + iota
    Units3_KM
)

func (r Units3Enum) MarshalJSON() ([]byte, error) { 
    s := Units3EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Units3Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Units3EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Units3Enum to its string representation
 */
func Units3EnumToValue(units3Enum Units3Enum) string {
    switch units3Enum {
        case Units3_MI:
    		return "MI"		
        case Units3_KM:
    		return "KM"		
        default:
        	return "MI"
    }
}

/**
 * Converts Units3Enum Array to its string Array representation
*/
func Units3EnumArrayToValue(units3Enum []Units3Enum) []string {
    convArray := make([]string,len( units3Enum))
    for i:=0; i<len(units3Enum);i++ {
        convArray[i] = Units3EnumToValue(units3Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Units3EnumFromValue(value string) Units3Enum {
    switch value {
        case "MI":
            return Units3_MI
        case "KM":
            return Units3_KM
        default:
            return Units3_MI
    }
}
