/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for WineOriginEnum enum
 */
type WineOriginEnum int

/**
 * Value collection for WineOriginEnum enum
 */
const (
    WineOrigin_ARGENTINA WineOriginEnum = 1 + iota
    WineOrigin_AUSTRALIA
    WineOrigin_AUSTRIA
    WineOrigin_CANADA
    WineOrigin_CHILE
    WineOrigin_CROATIA
    WineOrigin_ENUM_CZECH_REPUBLIC
    WineOrigin_ENGLAND
    WineOrigin_FRANCE
    WineOrigin_GERMANY
    WineOrigin_GREECE
    WineOrigin_HUNGARY
    WineOrigin_INDIA
    WineOrigin_ISRAEL
    WineOrigin_ITALY
    WineOrigin_JAPAN
    WineOrigin_LEBANON
    WineOrigin_LUXEMBOURG
    WineOrigin_MEXICO
    WineOrigin_MOROCCO
    WineOrigin_ENUM_NEW_ZEALAND
    WineOrigin_PORTUGAL
    WineOrigin_ENUM_REPUBLIC_OF_GEORGIA
    WineOrigin_ROMANIA
    WineOrigin_SERBIA
    WineOrigin_SLOVENIA
    WineOrigin_ENUM_SOUTH_AFRICA
    WineOrigin_SPAIN
    WineOrigin_SWITZERLAND
    WineOrigin_TURKEY
    WineOrigin_ENUM_UNITED_STATES
    WineOrigin_URUGUAY
    WineOrigin_UNKNOWN
)

func (r WineOriginEnum) MarshalJSON() ([]byte, error) { 
    s := WineOriginEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *WineOriginEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  WineOriginEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts WineOriginEnum to its string representation
 */
func WineOriginEnumToValue(wineOriginEnum WineOriginEnum) string {
    switch wineOriginEnum {
        case WineOrigin_ARGENTINA:
    		return "Argentina"		
        case WineOrigin_AUSTRALIA:
    		return "Australia"		
        case WineOrigin_AUSTRIA:
    		return "Austria"		
        case WineOrigin_CANADA:
    		return "Canada"		
        case WineOrigin_CHILE:
    		return "Chile"		
        case WineOrigin_CROATIA:
    		return "Croatia"		
        case WineOrigin_ENUM_CZECH_REPUBLIC:
    		return "Enum_Czech Republic"		
        case WineOrigin_ENGLAND:
    		return "England"		
        case WineOrigin_FRANCE:
    		return "France"		
        case WineOrigin_GERMANY:
    		return "Germany"		
        case WineOrigin_GREECE:
    		return "Greece"		
        case WineOrigin_HUNGARY:
    		return "Hungary"		
        case WineOrigin_INDIA:
    		return "India"		
        case WineOrigin_ISRAEL:
    		return "Israel"		
        case WineOrigin_ITALY:
    		return "Italy"		
        case WineOrigin_JAPAN:
    		return "Japan"		
        case WineOrigin_LEBANON:
    		return "Lebanon"		
        case WineOrigin_LUXEMBOURG:
    		return "Luxembourg"		
        case WineOrigin_MEXICO:
    		return "Mexico"		
        case WineOrigin_MOROCCO:
    		return "Morocco"		
        case WineOrigin_ENUM_NEW_ZEALAND:
    		return "Enum_New Zealand"		
        case WineOrigin_PORTUGAL:
    		return "Portugal"		
        case WineOrigin_ENUM_REPUBLIC_OF_GEORGIA:
    		return "Enum_Republic of Georgia"		
        case WineOrigin_ROMANIA:
    		return "Romania"		
        case WineOrigin_SERBIA:
    		return "Serbia"		
        case WineOrigin_SLOVENIA:
    		return "Slovenia"		
        case WineOrigin_ENUM_SOUTH_AFRICA:
    		return "Enum_South Africa"		
        case WineOrigin_SPAIN:
    		return "Spain"		
        case WineOrigin_SWITZERLAND:
    		return "Switzerland"		
        case WineOrigin_TURKEY:
    		return "Turkey"		
        case WineOrigin_ENUM_UNITED_STATES:
    		return "Enum_United States"		
        case WineOrigin_URUGUAY:
    		return "Uruguay"		
        case WineOrigin_UNKNOWN:
    		return "Unknown"		
        default:
        	return "Argentina"
    }
}

/**
 * Converts WineOriginEnum Array to its string Array representation
*/
func WineOriginEnumArrayToValue(wineOriginEnum []WineOriginEnum) []string {
    convArray := make([]string,len( wineOriginEnum))
    for i:=0; i<len(wineOriginEnum);i++ {
        convArray[i] = WineOriginEnumToValue(wineOriginEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func WineOriginEnumFromValue(value string) WineOriginEnum {
    switch value {
        case "Argentina":
            return WineOrigin_ARGENTINA
        case "Australia":
            return WineOrigin_AUSTRALIA
        case "Austria":
            return WineOrigin_AUSTRIA
        case "Canada":
            return WineOrigin_CANADA
        case "Chile":
            return WineOrigin_CHILE
        case "Croatia":
            return WineOrigin_CROATIA
        case "Enum_Czech_Republic":
            return WineOrigin_ENUM_CZECH_REPUBLIC
        case "England":
            return WineOrigin_ENGLAND
        case "France":
            return WineOrigin_FRANCE
        case "Germany":
            return WineOrigin_GERMANY
        case "Greece":
            return WineOrigin_GREECE
        case "Hungary":
            return WineOrigin_HUNGARY
        case "India":
            return WineOrigin_INDIA
        case "Israel":
            return WineOrigin_ISRAEL
        case "Italy":
            return WineOrigin_ITALY
        case "Japan":
            return WineOrigin_JAPAN
        case "Lebanon":
            return WineOrigin_LEBANON
        case "Luxembourg":
            return WineOrigin_LUXEMBOURG
        case "Mexico":
            return WineOrigin_MEXICO
        case "Morocco":
            return WineOrigin_MOROCCO
        case "Enum_New_Zealand":
            return WineOrigin_ENUM_NEW_ZEALAND
        case "Portugal":
            return WineOrigin_PORTUGAL
        case "Enum_Republic_of_Georgia":
            return WineOrigin_ENUM_REPUBLIC_OF_GEORGIA
        case "Romania":
            return WineOrigin_ROMANIA
        case "Serbia":
            return WineOrigin_SERBIA
        case "Slovenia":
            return WineOrigin_SLOVENIA
        case "Enum_South_Africa":
            return WineOrigin_ENUM_SOUTH_AFRICA
        case "Spain":
            return WineOrigin_SPAIN
        case "Switzerland":
            return WineOrigin_SWITZERLAND
        case "Turkey":
            return WineOrigin_TURKEY
        case "Enum_United_States":
            return WineOrigin_ENUM_UNITED_STATES
        case "Uruguay":
            return WineOrigin_URUGUAY
        case "Unknown":
            return WineOrigin_UNKNOWN
        default:
            return WineOrigin_ARGENTINA
    }
}
