/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for WineTypeEnum enum
 */
type WineTypeEnum int

/**
 * Value collection for WineTypeEnum enum
 */
const (
    WineType_ENUM_STILL_WINE WineTypeEnum = 1 + iota
    WineType_NONALCOHOLIC
    WineType_ENUM_SPARKLING_WINE
    WineType_ENUM_FORTIFIED_WINE
)

func (r WineTypeEnum) MarshalJSON() ([]byte, error) { 
    s := WineTypeEnumToValue(r)
    return json.Marshal(s) 
} 

func (r *WineTypeEnum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  WineTypeEnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts WineTypeEnum to its string representation
 */
func WineTypeEnumToValue(wineTypeEnum WineTypeEnum) string {
    switch wineTypeEnum {
        case WineType_ENUM_STILL_WINE:
    		return "Enum_Still Wine"		
        case WineType_NONALCOHOLIC:
    		return "NonAlcoholic"		
        case WineType_ENUM_SPARKLING_WINE:
    		return "Enum_Sparkling Wine"		
        case WineType_ENUM_FORTIFIED_WINE:
    		return "Enum_Fortified Wine"		
        default:
        	return "Enum_Still Wine"
    }
}

/**
 * Converts WineTypeEnum Array to its string Array representation
*/
func WineTypeEnumArrayToValue(wineTypeEnum []WineTypeEnum) []string {
    convArray := make([]string,len( wineTypeEnum))
    for i:=0; i<len(wineTypeEnum);i++ {
        convArray[i] = WineTypeEnumToValue(wineTypeEnum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func WineTypeEnumFromValue(value string) WineTypeEnum {
    switch value {
        case "Enum_Still_Wine":
            return WineType_ENUM_STILL_WINE
        case "NonAlcoholic":
            return WineType_NONALCOHOLIC
        case "Enum_Sparkling_Wine":
            return WineType_ENUM_SPARKLING_WINE
        case "Enum_Fortified_Wine":
            return WineType_ENUM_FORTIFIED_WINE
        default:
            return WineType_ENUM_STILL WINE
    }
}
