/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AltLocationTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    HAL: 'HAL',

    /**
     * TODO: Write general description for this element
     */
    ACP: 'ACP',

};

module.exports = AltLocationTypeEnum;
