/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of BolInboundCreatePayload
 */
class BolInboundCreatePayload extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.referenceId = this.constructor.getValue(obj.referenceId || obj.reference_id);
        this.clientId = this.constructor.getValue(obj.clientId || obj.client_id);
        this.shipmentId = this.constructor.getValue(obj.shipmentId || obj.shipment_id);
        this.dayOfDelivery = this.constructor.getValue(obj.dayOfDelivery || obj.day_of_delivery);
        this.dayOfDeliveryUntil =
          this.constructor.getValue(obj.dayOfDeliveryUntil
     || obj.day_of_delivery_until);
        this.deliveryNoteNumber =
          this.constructor.getValue(obj.deliveryNoteNumber
     || obj.delivery_note_number);
        this.type = this.constructor.getValue(obj.type, 'REGULAR');
        this.comment = this.constructor.getValue(obj.comment);
        this.supplier = this.constructor.getValue(obj.supplier);
        this.positions = this.constructor.getValue(obj.positions);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'referenceId', realName: 'reference_id' },
            { name: 'clientId', realName: 'client_id' },
            { name: 'shipmentId', realName: 'shipment_id' },
            { name: 'dayOfDelivery', realName: 'day_of_delivery', isDateTime: true },
            { name: 'dayOfDeliveryUntil', realName: 'day_of_delivery_until', isDateTime: true },
            { name: 'deliveryNoteNumber', realName: 'delivery_note_number' },
            { name: 'type', realName: 'type' },
            { name: 'comment', realName: 'comment' },
            { name: 'supplier', realName: 'supplier' },
            {
                name: 'positions',
                realName: 'positions',
                array: true,
                type: 'BolInboundRequestPosition',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = BolInboundCreatePayload;
