/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const FoodTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    BEVERAGE: 'Beverage',

    /**
     * TODO: Write general description for this element
     */
    CANNED: 'Canned',

    /**
     * TODO: Write general description for this element
     */
    DAIRY: 'Dairy',

    /**
     * TODO: Write general description for this element
     */
    DESSERT: 'Dessert',

    /**
     * TODO: Write general description for this element
     */
    FRUIT: 'Fruit',

    /**
     * TODO: Write general description for this element
     */
    MEAT: 'Meat',

    /**
     * TODO: Write general description for this element
     */
    PRODUCE: 'Produce',

    /**
     * TODO: Write general description for this element
     */
    SEAFOOD: 'Seafood',

    /**
     * TODO: Write general description for this element
     */
    OTHER: 'Other',

};

module.exports = FoodTypeEnum;
