/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const FulfillmentTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_WILL_CALL: 'Will Call',

    /**
     * TODO: Write general description for this element
     */
    ENUM_DTC_DIRECT_SHIP: 'DTC-Direct Ship',

    /**
     * TODO: Write general description for this element
     */
    ENUM_DTC_TEMP_CONTROL: 'DTC-Temp Control',

    /**
     * TODO: Write general description for this element
     */
    ENUM_3_TIER: '3Tier',

    /**
     * TODO: Write general description for this element
     */
    DTT: 'DTT',

    /**
     * TODO: Write general description for this element
     */
    TRANSFER: 'Transfer',

};

module.exports = FulfillmentTypeEnum;
