/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Location
 */
class Location extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.address1 = this.constructor.getValue(obj.address1);
        this.address2 = this.constructor.getValue(obj.address2);
        this.city = this.constructor.getValue(obj.city);
        this.state = this.constructor.getValue(obj.state);
        this.postalCode = this.constructor.getValue(obj.postalCode);
        this.country = this.constructor.getValue(obj.country);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'address1', realName: 'address1' },
            { name: 'address2', realName: 'address2' },
            { name: 'city', realName: 'city' },
            { name: 'state', realName: 'state' },
            { name: 'postalCode', realName: 'postalCode' },
            { name: 'country', realName: 'country' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Location;
