/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const MessageTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    PROCESSED: 'Processed',

    /**
     * TODO: Write general description for this element
     */
    SHIPPED: 'Shipped',

    /**
     * TODO: Write general description for this element
     */
    EXCEPTION: 'Exception',

    /**
     * TODO: Write general description for this element
     */
    RETURNED: 'Returned',

    /**
     * TODO: Write general description for this element
     */
    ENUM_DELIVERY_ATTEMPT: 'Delivery Attempt',

    /**
     * TODO: Write general description for this element
     */
    ENUM_OUT_FOR_DELIVERY: 'Out for Delivery',

    /**
     * TODO: Write general description for this element
     */
    DELIVERED: 'Delivered',

};

module.exports = MessageTypeEnum;
