/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of OrderItem
 */
class OrderItem extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.productSKU = this.constructor.getValue(obj.productSKU);
        this.quantity = this.constructor.getValue(obj.quantity);
        this.productSupplier = this.constructor.getValue(obj.productSupplier);
        this.productName = this.constructor.getValue(obj.productName);
        this.tax = this.constructor.getValue(obj.tax);
        this.price = this.constructor.getValue(obj.price);
        this.pctAlcohol = this.constructor.getValue(obj.pctAlcohol);
        this.weight = this.constructor.getValue(obj.weight);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'productSKU', realName: 'productSKU' },
            { name: 'quantity', realName: 'quantity' },
            { name: 'productSupplier', realName: 'productSupplier' },
            { name: 'productName', realName: 'productName' },
            { name: 'tax', realName: 'tax' },
            { name: 'price', realName: 'price' },
            { name: 'pctAlcohol', realName: 'pctAlcohol' },
            { name: 'weight', realName: 'weight' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = OrderItem;
