/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const OrderTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    CLUB: 'Club',

    /**
     * TODO: Write general description for this element
     */
    E_COMMERCE: 'E-Commerce',

    /**
     * TODO: Write general description for this element
     */
    RETAIL: 'Retail',

    /**
     * TODO: Write general description for this element
     */
    ENUM_TASTING_ROOM: 'Tasting Room',

    /**
     * TODO: Write general description for this element
     */
    ENUM_NA: 'N/A',

    /**
     * TODO: Write general description for this element
     */
    WEBSITE: 'Website',

};

module.exports = OrderTypeEnum;
