/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const PendingEnum = {

    /**
     * TODO: Write general description for this element
     */
    Y: 'Y',

    /**
     * TODO: Write general description for this element
     */
    N: 'N',

};

module.exports = PendingEnum;
