/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ProductTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    WINE: 'Wine',

    /**
     * TODO: Write general description for this element
     */
    FOOD: 'Food',

    /**
     * TODO: Write general description for this element
     */
    MERCHANDISE: 'Merchandise',

    /**
     * TODO: Write general description for this element
     */
    COLLATERAL: 'Collateral',

};

module.exports = ProductTypeEnum;
