/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of RejectedOrderDescription
 */
class RejectedOrderDescription extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.dateInvalidDate = this.constructor.getValue(obj.dateInvalidDate);
        this.isEmpty = this.constructor.getValue(obj.isEmpty);
        this.noRecordFound = this.constructor.getValue(obj.noRecordFound);
        this.callbackValue = this.constructor.getValue(obj.callbackValue);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'dateInvalidDate', realName: 'dateInvalidDate' },
            { name: 'isEmpty', realName: 'isEmpty' },
            { name: 'noRecordFound', realName: 'noRecordFound' },
            { name: 'callbackValue', realName: 'callbackValue' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = RejectedOrderDescription;
