/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Results5
 */
class Results5 extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.messageCount = this.constructor.getValue(obj.messageCount);
        this.endTime = this.constructor.getValue(obj.endTime);
        this.messages = this.constructor.getValue(obj.messages);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'messageCount', realName: 'messageCount' },
            { name: 'endTime', realName: 'endTime', isDateTime: true, dateTimeValue: 'rfc3339' },
            { name: 'messages', realName: 'messages', array: true, type: 'Message2' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Results5;
