/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const RouteDirectionEnum = {

    /**
     * TODO: Write general description for this element
     */
    PASS: 'pass',

    /**
     * TODO: Write general description for this element
     */
    REJECT: 'reject',

    /**
     * TODO: Write general description for this element
     */
    STOP: 'stop',

};

module.exports = RouteDirectionEnum;
