/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ShipMethodEnum = {

    /**
     * TODO: Write general description for this element
     */
    UP_2: 'UP2',

    /**
     * TODO: Write general description for this element
     */
    UP_3: 'UP3',

    /**
     * TODO: Write general description for this element
     */
    UPS: 'UPS',

    /**
     * TODO: Write general description for this element
     */
    UP_1: 'UP1',

    /**
     * TODO: Write general description for this element
     */
    UPS_7: 'UPS7',

    /**
     * TODO: Write general description for this element
     */
    FEX: 'FEX',

    /**
     * TODO: Write general description for this element
     */
    FXE: 'FXE',

    /**
     * TODO: Write general description for this element
     */
    FXG: 'FXG',

    /**
     * TODO: Write general description for this element
     */
    FEH: 'FEH',

    /**
     * TODO: Write general description for this element
     */
    FXP: 'FXP',

    /**
     * TODO: Write general description for this element
     */
    FXO: 'FXO',

    /**
     * TODO: Write general description for this element
     */
    GSC: 'GSC',

    /**
     * TODO: Write general description for this element
     */
    GSP: 'GSP',

    /**
     * TODO: Write general description for this element
     */
    GSO_3: 'GSO3',

    /**
     * TODO: Write general description for this element
     */
    WCP: 'WCP',

    /**
     * TODO: Write general description for this element
     */
    WCU: 'WCU',

    /**
     * TODO: Write general description for this element
     */
    WCX: 'WCX',

    /**
     * TODO: Write general description for this element
     */
    UDS: 'UDS',

    /**
     * TODO: Write general description for this element
     */
    AZS: 'AZS',

    /**
     * TODO: Write general description for this element
     */
    TRANSFER: 'Transfer',

};

module.exports = ShipMethodEnum;
