/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const SlotEquivalentEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_0_ML: '0ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_7_ML: '7ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_50_ML: '50ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_100_ML: '100ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_125_ML: '125ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_147_ML: '147ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_187_ML: '187ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_200_ML: '200ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_250_ML: '250ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_300_ML: '300ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_330_ML: '330ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_333_ML: '333ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_341_ML: '341ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_350_ML: '350ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_355_ML: '355ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_375_ML: '375ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_376_ML: '376ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_500_ML: '500ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_620_ML: '620ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_650_ML: '650ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_680_ML: '680ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_700_ML: '700ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_720_ML: '720ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_750_ML: '750ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_751_ML: '751ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_800_ML: '800ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1000_ML: '1000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1500_ML: '1500ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1750_ML: '1750ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1800_ML: '1800ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1875_ML: '1875ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_2000_ML: '2000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_3000_ML: '3000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_4500_ML: '4500ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_5000_ML: '5000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_6000_ML: '6000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_9000_ML: '9000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_10000_ML: '10000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_12000_ML: '12000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_15000_ML: '15000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_18000_ML: '18000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_19500_ML: '19500ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_20000_ML: '20000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_27000_ML: '27000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_50000_ML: '50000ml',

    /**
     * TODO: Write general description for this element
     */
    ENUM_56000_ML: '56000ml',

};

module.exports = SlotEquivalentEnum;
