/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const StatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    SUCCESS: 'success',

    /**
     * TODO: Write general description for this element
     */
    PARTIAL: 'partial',

    /**
     * TODO: Write general description for this element
     */
    FAILURE: 'failure',

};

module.exports = StatusEnum;
