/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Status2Enum = {

    /**
     * TODO: Write general description for this element
     */
    FAILURE: 'failure',

    /**
     * TODO: Write general description for this element
     */
    SUCCESS: 'success',

};

module.exports = Status2Enum;
