/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Type8Enum = {

    /**
     * TODO: Write general description for this element
     */
    REGULAR: 'REGULAR',

    /**
     * TODO: Write general description for this element
     */
    MRETURN: 'RETURN',

};

module.exports = Type8Enum;
