/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const UnitsEnum = {

    /**
     * TODO: Write general description for this element
     */
    POUNDS: 'pounds',

};

module.exports = UnitsEnum;
