/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Units3Enum = {

    /**
     * TODO: Write general description for this element
     */
    MI: 'MI',

    /**
     * TODO: Write general description for this element
     */
    KM: 'KM',

};

module.exports = Units3Enum;
