/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const WineOriginEnum = {

    /**
     * TODO: Write general description for this element
     */
    ARGENTINA: 'Argentina',

    /**
     * TODO: Write general description for this element
     */
    AUSTRALIA: 'Australia',

    /**
     * TODO: Write general description for this element
     */
    AUSTRIA: 'Austria',

    /**
     * TODO: Write general description for this element
     */
    CANADA: 'Canada',

    /**
     * TODO: Write general description for this element
     */
    CHILE: 'Chile',

    /**
     * TODO: Write general description for this element
     */
    CROATIA: 'Croatia',

    /**
     * TODO: Write general description for this element
     */
    ENUM_CZECH_REPUBLIC: 'Czech Republic',

    /**
     * TODO: Write general description for this element
     */
    ENGLAND: 'England',

    /**
     * TODO: Write general description for this element
     */
    FRANCE: 'France',

    /**
     * TODO: Write general description for this element
     */
    GERMANY: 'Germany',

    /**
     * TODO: Write general description for this element
     */
    GREECE: 'Greece',

    /**
     * TODO: Write general description for this element
     */
    HUNGARY: 'Hungary',

    /**
     * TODO: Write general description for this element
     */
    INDIA: 'India',

    /**
     * TODO: Write general description for this element
     */
    ISRAEL: 'Israel',

    /**
     * TODO: Write general description for this element
     */
    ITALY: 'Italy',

    /**
     * TODO: Write general description for this element
     */
    JAPAN: 'Japan',

    /**
     * TODO: Write general description for this element
     */
    LEBANON: 'Lebanon',

    /**
     * TODO: Write general description for this element
     */
    LUXEMBOURG: 'Luxembourg',

    /**
     * TODO: Write general description for this element
     */
    MEXICO: 'Mexico',

    /**
     * TODO: Write general description for this element
     */
    MOROCCO: 'Morocco',

    /**
     * TODO: Write general description for this element
     */
    ENUM_NEW_ZEALAND: 'New Zealand',

    /**
     * TODO: Write general description for this element
     */
    PORTUGAL: 'Portugal',

    /**
     * TODO: Write general description for this element
     */
    ENUM_REPUBLIC_OF_GEORGIA: 'Republic of Georgia',

    /**
     * TODO: Write general description for this element
     */
    ROMANIA: 'Romania',

    /**
     * TODO: Write general description for this element
     */
    SERBIA: 'Serbia',

    /**
     * TODO: Write general description for this element
     */
    SLOVENIA: 'Slovenia',

    /**
     * TODO: Write general description for this element
     */
    ENUM_SOUTH_AFRICA: 'South Africa',

    /**
     * TODO: Write general description for this element
     */
    SPAIN: 'Spain',

    /**
     * TODO: Write general description for this element
     */
    SWITZERLAND: 'Switzerland',

    /**
     * TODO: Write general description for this element
     */
    TURKEY: 'Turkey',

    /**
     * TODO: Write general description for this element
     */
    ENUM_UNITED_STATES: 'United States',

    /**
     * TODO: Write general description for this element
     */
    URUGUAY: 'Uruguay',

    /**
     * TODO: Write general description for this element
     */
    UNKNOWN: 'Unknown',

};

module.exports = WineOriginEnum;
