/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const WineTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_STILL_WINE: 'Still Wine',

    /**
     * TODO: Write general description for this element
     */
    NON_ALCOHOLIC: 'Non-Alcoholic',

    /**
     * TODO: Write general description for this element
     */
    ENUM_SPARKLING_WINE: 'Sparkling Wine',

    /**
     * TODO: Write general description for this element
     */
    ENUM_FORTIFIED_WINE: 'Fortified Wine',

};

module.exports = WineTypeEnum;
