/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ProductCreateRequest = require('./ProductCreateRequest');

/**
 * Creates an instance of Wine
 */
class Wine extends ProductCreateRequest {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.wineVintage = this.constructor.getValue(obj.wineVintage);
        this.wineType = this.constructor.getValue(obj.wineType);
        this.pctAlcohol = this.constructor.getValue(obj.pctAlcohol);
        this.wineOrigin = this.constructor.getValue(obj.wineOrigin);
        this.wineVineyard = this.constructor.getValue(obj.wineVineyard);
        this.wineBottleSize = this.constructor.getValue(obj.wineBottleSize);
        this.wineCOLA = this.constructor.getValue(obj.wineCOLA);
        this.wineVarietal = this.constructor.getValue(obj.wineVarietal);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'wineVintage', realName: 'wineVintage' },
            { name: 'wineType', realName: 'wineType' },
            { name: 'pctAlcohol', realName: 'pctAlcohol' },
            { name: 'wineOrigin', realName: 'wineOrigin' },
            { name: 'wineVineyard', realName: 'wineVineyard' },
            { name: 'wineBottleSize', realName: 'wineBottleSize' },
            { name: 'wineCOLA', realName: 'wineCOLA' },
            { name: 'wineVarietal', realName: 'wineVarietal' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {
            Wine: 'Wine',
        };
    }
}

module.exports = Wine;
