/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Merchandise = require('../lib/Models/Merchandise');
const Response = require('../lib/Models/Response');
const Results = require('../lib/Models/Results');
const ProductUpdateResponseSuccess = require('../lib/Models/ProductUpdateResponseSuccess');
const ProductDetailsRequest = require('../lib/Models/ProductDetailsRequest');
const ParcelStatusItem = require('../lib/Models/ParcelStatusItem');
const ParcelStatus1 = require('../lib/Models/ParcelStatus1');
const ParcelStatus = require('../lib/Models/ParcelStatus');
const ParcelCheckWeightGoodResponse = require('../lib/Models/ParcelCheckWeightGoodResponse');
const OrderStatusResponse1 = require('../lib/Models/OrderStatusResponse1');
const OrderStatusRequest = require('../lib/Models/OrderStatusRequest');
const OrderStatusResponse = require('../lib/Models/OrderStatusResponse');
const SalesOrderResponse = require('../lib/Models/SalesOrderResponse');
const Results5 = require('../lib/Models/Results5');
const Results1 = require('../lib/Models/Results1');
const Result2 = require('../lib/Models/Result2');
const Result = require('../lib/Models/Result');
const Orders = require('../lib/Models/Orders');
const OrderItem1 = require('../lib/Models/OrderItem1');
const RejectedOrderDescription = require('../lib/Models/RejectedOrderDescription');
const InventoryItem = require('../lib/Models/InventoryItem');
const Address2 = require('../lib/Models/Address2');
const PickupAddress = require('../lib/Models/PickupAddress');
const ShippingAddress = require('../lib/Models/ShippingAddress');
const Address = require('../lib/Models/Address');
const Order = require('../lib/Models/Order');
const Results4 = require('../lib/Models/Results4');
const Results3 = require('../lib/Models/Results3');
const Result1 = require('../lib/Models/Result1');
const ProductUpdateRequest = require('../lib/Models/ProductUpdateRequest');
const OrderStatusItem1 = require('../lib/Models/OrderStatusItem1');
const OrderStatusItem = require('../lib/Models/OrderStatusItem');
const OrderItem = require('../lib/Models/OrderItem');
const BolInboundCreatePayload = require('../lib/Models/BolInboundCreatePayload');
const Wine = require('../lib/Models/Wine');
const ProductCreateRequest = require('../lib/Models/ProductCreateRequest');
const InventoryRequest = require('../lib/Models/InventoryRequest');
const RejectedOrder = require('../lib/Models/RejectedOrder');
const InventoryResponse = require('../lib/Models/InventoryResponse');
const ProductDetailsResponse = require('../lib/Models/ProductDetailsResponse');
const ProductDetailsItem = require('../lib/Models/ProductDetailsItem');
const GetNotificationsResponse = require('../lib/Models/GetNotificationsResponse');
const ParcelStatusItem1 = require('../lib/Models/ParcelStatusItem1');
const DeficientSku = require('../lib/Models/DeficientSku');
const CancelRequest = require('../lib/Models/CancelRequest');
const BolInboundCreateSuccessResponse = require('../lib/Models/BolInboundCreateSuccessResponse');
const BolInboundCreateRequest = require('../lib/Models/BolInboundCreateRequest');
const CancelResponse = require('../lib/Models/CancelResponse');
const AlternatePickupLocationsResponse = require('../lib/Models/AlternatePickupLocationsResponse');
const AcceptedOrder = require('../lib/Models/AcceptedOrder');
const Message2 = require('../lib/Models/Message2');
const ProductCreateResponse = require('../lib/Models/ProductCreateResponse');
const MError = require('../lib/Models/MError');
const Location = require('../lib/Models/Location');
const GetNotificationsRequest = require('../lib/Models/GetNotificationsRequest');
const GenericError = require('../lib/Models/GenericError');
const BolInboundRequestPosition = require('../lib/Models/BolInboundRequestPosition');
const AlternatePickupLocationsRequest = require('../lib/Models/AlternatePickupLocationsRequest');
const Food = require('../lib/Models/Food');
const TrackingItem = require('../lib/Models/TrackingItem');
const TrackingResponseItem = require('../lib/Models/TrackingResponseItem');
const TrackingResponse = require('../lib/Models/TrackingResponse');
const Collateral = require('../lib/Models/Collateral');
const TrackingRequest = require('../lib/Models/TrackingRequest');
const ProductUpdateResponseFailureException =
  require('../lib/Exceptions/ProductUpdateResponseFailureException');
const ParcelCheckWeightBadResponseException =
  require('../lib/Exceptions/ParcelCheckWeightBadResponseException');
const OrderStatusResponse1ErrorException =
  require('../lib/Exceptions/OrderStatusResponse1ErrorException');
const Error1Exception = require('../lib/Exceptions/Error1Exception');
const ProductDetailsErrorResponseException =
  require('../lib/Exceptions/ProductDetailsErrorResponseException');
const AlternatePickupLocationsErrorResponseException =
  require('../lib/Exceptions/AlternatePickupLocationsErrorResponseException');
const ProductCreateFailureResponseException =
  require('../lib/Exceptions/ProductCreateFailureResponseException');
const GenericError2Exception = require('../lib/Exceptions/GenericError2Exception');

const classMap = {
    Merchandise,
    Response,
    Results,
    ProductUpdateResponseSuccess,
    ProductDetailsRequest,
    ParcelStatusItem,
    ParcelStatus1,
    ParcelStatus,
    ParcelCheckWeightGoodResponse,
    OrderStatusResponse1,
    OrderStatusRequest,
    OrderStatusResponse,
    SalesOrderResponse,
    Results5,
    Results1,
    Result2,
    Result,
    Orders,
    OrderItem1,
    RejectedOrderDescription,
    InventoryItem,
    Address2,
    PickupAddress,
    ShippingAddress,
    Address,
    Order,
    Results4,
    Results3,
    Result1,
    ProductUpdateRequest,
    OrderStatusItem1,
    OrderStatusItem,
    OrderItem,
    BolInboundCreatePayload,
    Wine,
    ProductCreateRequest,
    InventoryRequest,
    RejectedOrder,
    InventoryResponse,
    ProductDetailsResponse,
    ProductDetailsItem,
    GetNotificationsResponse,
    ParcelStatusItem1,
    DeficientSku,
    CancelRequest,
    BolInboundCreateSuccessResponse,
    BolInboundCreateRequest,
    CancelResponse,
    AlternatePickupLocationsResponse,
    AcceptedOrder,
    Message2,
    ProductCreateResponse,
    MError,
    Location,
    GetNotificationsRequest,
    GenericError,
    BolInboundRequestPosition,
    AlternatePickupLocationsRequest,
    Food,
    TrackingItem,
    TrackingResponseItem,
    TrackingResponse,
    Collateral,
    TrackingRequest,
    ProductUpdateResponseFailureException,
    ParcelCheckWeightBadResponseException,
    OrderStatusResponse1ErrorException,
    Error1Exception,
    ProductDetailsErrorResponseException,
    AlternatePickupLocationsErrorResponseException,
    ProductCreateFailureResponseException,
    GenericError2Exception,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
