/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using ProNimbusAPI.Standard.Controllers;
using ProNimbusAPI.Standard.Http.Client;
using ProNimbusAPI.Standard.Utilities;

namespace ProNimbusAPI.Standard
{
    public partial class ProNimbusAPIClient
    {

        /// <summary>
        /// Singleton access to SKU controller
        /// </summary>
        public SKUController SKU
        {
            get
            {
                return SKUController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Notifications controller
        /// </summary>
        public NotificationsController Notifications
        {
            get
            {
                return NotificationsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Inventory controller
        /// </summary>
        public InventoryController Inventory
        {
            get
            {
                return InventoryController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SalesOrder controller
        /// </summary>
        public SalesOrderController SalesOrder
        {
            get
            {
                return SalesOrderController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public ProNimbusAPIClient() { }
        #endregion
    }
}