/*
 * pronimbusapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package ProNimbusAPIClient

import(
	"pronimbusapi_lib/configuration_pkg"
	"pronimbusapi_lib/sku_pkg"
	"pronimbusapi_lib/notifications_pkg"
	"pronimbusapi_lib/inventory_pkg"
	"pronimbusapi_lib/salesorder_pkg"
)


/*
 * Interface for the PRONIMBUSAPI_IMPL
 */
type PRONIMBUSAPI interface {
    SKU()                   sku_pkg.SKU
    Notifications()         notifications_pkg.NOTIFICATIONS
    Inventory()             inventory_pkg.INVENTORY
    SalesOrder()            salesorder_pkg.SALESORDER
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the PRONIMBUSAPI interface returning PRONIMBUSAPI_IMPL
 */
func NewPRONIMBUSAPI() PRONIMBUSAPI {
    proNimbusAPIClient := new(PRONIMBUSAPI_IMPL)
    proNimbusAPIClient.config = configuration_pkg.NewCONFIGURATION()

    return proNimbusAPIClient
}
