/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class BolInboundCreatePayload : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string referenceId;
        private string clientId;
        private string shipmentId;
        private DateTime? dayOfDelivery;
        private DateTime? dayOfDeliveryUntil;
        private string deliveryNoteNumber;
        private Models.Type8Enum type = Models.Type8Enum.REGULAR;
        private string comment;
        private string supplier;
        private List<Models.BolInboundRequestPosition> positions;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("reference_id")]
        public string ReferenceId 
        { 
            get 
            {
                return this.referenceId; 
            } 
            set 
            {
                this.referenceId = value;
                onPropertyChanged("ReferenceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("client_id")]
        public string ClientId 
        { 
            get 
            {
                return this.clientId; 
            } 
            set 
            {
                this.clientId = value;
                onPropertyChanged("ClientId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("shipment_id")]
        public string ShipmentId 
        { 
            get 
            {
                return this.shipmentId; 
            } 
            set 
            {
                this.shipmentId = value;
                onPropertyChanged("ShipmentId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("day_of_delivery")]
        public DateTime? DayOfDelivery 
        { 
            get 
            {
                return this.dayOfDelivery; 
            } 
            set 
            {
                this.dayOfDelivery = value;
                onPropertyChanged("DayOfDelivery");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("day_of_delivery_until")]
        public DateTime? DayOfDeliveryUntil 
        { 
            get 
            {
                return this.dayOfDeliveryUntil; 
            } 
            set 
            {
                this.dayOfDeliveryUntil = value;
                onPropertyChanged("DayOfDeliveryUntil");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("delivery_note_number")]
        public string DeliveryNoteNumber 
        { 
            get 
            {
                return this.deliveryNoteNumber; 
            } 
            set 
            {
                this.deliveryNoteNumber = value;
                onPropertyChanged("DeliveryNoteNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("type", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.Type8Enum Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("comment")]
        public string Comment 
        { 
            get 
            {
                return this.comment; 
            } 
            set 
            {
                this.comment = value;
                onPropertyChanged("Comment");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("supplier")]
        public string Supplier 
        { 
            get 
            {
                return this.supplier; 
            } 
            set 
            {
                this.supplier = value;
                onPropertyChanged("Supplier");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("positions")]
        public List<Models.BolInboundRequestPosition> Positions 
        { 
            get 
            {
                return this.positions; 
            } 
            set 
            {
                this.positions = value;
                onPropertyChanged("Positions");
            }
        }
    }
} 