/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class BolInboundRequestPosition : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string referenceId;
        private string sku;
        private string boxId;
        private int? amountOfBoxes = 3;
        private int? amountOfBottles = 36;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("reference_id")]
        public string ReferenceId 
        { 
            get 
            {
                return this.referenceId; 
            } 
            set 
            {
                this.referenceId = value;
                onPropertyChanged("ReferenceId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sku")]
        public string Sku 
        { 
            get 
            {
                return this.sku; 
            } 
            set 
            {
                this.sku = value;
                onPropertyChanged("Sku");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("box_id")]
        public string BoxId 
        { 
            get 
            {
                return this.boxId; 
            } 
            set 
            {
                this.boxId = value;
                onPropertyChanged("BoxId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount_of_boxes")]
        public int? AmountOfBoxes 
        { 
            get 
            {
                return this.amountOfBoxes; 
            } 
            set 
            {
                this.amountOfBoxes = value;
                onPropertyChanged("AmountOfBoxes");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("amount_of_bottles")]
        public int? AmountOfBottles 
        { 
            get 
            {
                return this.amountOfBottles; 
            } 
            set 
            {
                this.amountOfBottles = value;
                onPropertyChanged("AmountOfBottles");
            }
        }
    }
} 