/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class Collateral : ProductCreateRequest 
    {
        // These fields hold the values for the public properties.
        private Models.CollateralTypeEnum collateralType;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("collateralType", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.CollateralTypeEnum CollateralType 
        { 
            get 
            {
                return this.collateralType; 
            } 
            set 
            {
                this.collateralType = value;
                onPropertyChanged("CollateralType");
            }
        }
    }
} 