/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;

namespace ProNimbusAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum FulfillmentTypeEnum
    {
        ENUM_WILL_CALL, //TODO: Write general description for this method
        ENUM_DTCDIRECT_SHIP, //TODO: Write general description for this method
        ENUM_DTCTEMP_CONTROL, //TODO: Write general description for this method
        ENUM_3TIER, //TODO: Write general description for this method
        DTT, //TODO: Write general description for this method
        TRANSFER, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type FulfillmentTypeEnum
    /// </summary>
    public static class FulfillmentTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "Will Call", "DTC-Direct Ship", "DTC-Temp Control", "3Tier", "DTT", "Transfer" };

        /// <summary>
        /// Converts a FulfillmentTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The FulfillmentTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(FulfillmentTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case FulfillmentTypeEnum.ENUM_WILL_CALL:
                case FulfillmentTypeEnum.ENUM_DTCDIRECT_SHIP:
                case FulfillmentTypeEnum.ENUM_DTCTEMP_CONTROL:
                case FulfillmentTypeEnum.ENUM_3TIER:
                case FulfillmentTypeEnum.DTT:
                case FulfillmentTypeEnum.TRANSFER:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of FulfillmentTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of FulfillmentTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<FulfillmentTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into FulfillmentTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed FulfillmentTypeEnum value</returns>
        public static FulfillmentTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type FulfillmentTypeEnum", value));

            return (FulfillmentTypeEnum) index;
        }
    }
} 