/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class GetNotificationsRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string clientCode;
        private Models.RequestTypeEnum requestType;
        private DateTime startTime;
        private DateTime? endTime;

        /// <summary>
        /// Unique client identifier
        /// </summary>
        [JsonProperty("clientCode")]
        public string ClientCode 
        { 
            get 
            {
                return this.clientCode; 
            } 
            set 
            {
                this.clientCode = value;
                onPropertyChanged("ClientCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("requestType", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.RequestTypeEnum RequestType 
        { 
            get 
            {
                return this.requestType; 
            } 
            set 
            {
                this.requestType = value;
                onPropertyChanged("RequestType");
            }
        }

        /// <summary>
        /// Return all consignee emails sent during the date/time interval starting at
        /// `startTime` and ending at `endTime`. Maximum of 2 days' worth of data can be requested. Timestamp must be
        /// in [RFC3339](https://tools.ietf.org/html/rfc3339) format, i.e. `2018-02-18T00:00:00EST`.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("startTime")]
        public DateTime StartTime 
        { 
            get 
            {
                return this.startTime; 
            } 
            set 
            {
                this.startTime = value;
                onPropertyChanged("StartTime");
            }
        }

        /// <summary>
        /// Optional. Defaults to the current time if omitted.
        /// Return all consignee emails sent during the date range starting at
        /// `startTime` and ending at `endTime`. Timestamp must be
        /// in [RFC3339](https://tools.ietf.org/html/rfc3339) format, i.e. `2018-02-18T00:00:00EST`.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("endTime")]
        public DateTime? EndTime 
        { 
            get 
            {
                return this.endTime; 
            } 
            set 
            {
                this.endTime = value;
                onPropertyChanged("EndTime");
            }
        }
    }
} 