/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;

namespace ProNimbusAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum GiftEnum
    {
        Y, //TODO: Write general description for this method
        N, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type GiftEnum
    /// </summary>
    public static class GiftEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "Y", "N" };

        /// <summary>
        /// Converts a GiftEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The GiftEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(GiftEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case GiftEnum.Y:
                case GiftEnum.N:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of GiftEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of GiftEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<GiftEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into GiftEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed GiftEnum value</returns>
        public static GiftEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type GiftEnum", value));

            return (GiftEnum) index;
        }
    }
} 