/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class InventoryRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string clientCode;
        private string facility;
        private List<string> sku;

        /// <summary>
        /// Unique client identifier
        /// </summary>
        [JsonProperty("clientCode")]
        public string ClientCode 
        { 
            get 
            {
                return this.clientCode; 
            } 
            set 
            {
                this.clientCode = value;
                onPropertyChanged("ClientCode");
            }
        }

        /// <summary>
        /// The code that defines the facility to return inventory records for. If omitted, returns inventory records for **all** facilities.
        /// </summary>
        [JsonProperty("facility")]
        public string Facility 
        { 
            get 
            {
                return this.facility; 
            } 
            set 
            {
                this.facility = value;
                onPropertyChanged("Facility");
            }
        }

        /// <summary>
        /// List of SKUs to query inventory for. If omitted, returns inventory records for **all** SKUs in the facility specified.
        /// </summary>
        [JsonProperty("sku")]
        public List<string> Sku 
        { 
            get 
            {
                return this.sku; 
            } 
            set 
            {
                this.sku = value;
                onPropertyChanged("Sku");
            }
        }
    }
} 