/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class Message2 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string orderID;
        private string toName;
        private string toEmail;
        private string fromName;
        private string fromEmail;
        private DateTime? timeSent;
        private Models.MessageTypeEnum? messageType;
        private string subject;
        private string body;

        /// <summary>
        /// Customer order number.
        /// </summary>
        [JsonProperty("orderID")]
        public string OrderID 
        { 
            get 
            {
                return this.orderID; 
            } 
            set 
            {
                this.orderID = value;
                onPropertyChanged("OrderID");
            }
        }

        /// <summary>
        /// Name of email recipient
        /// </summary>
        [JsonProperty("toName")]
        public string ToName 
        { 
            get 
            {
                return this.toName; 
            } 
            set 
            {
                this.toName = value;
                onPropertyChanged("ToName");
            }
        }

        /// <summary>
        /// Email address of email recipient
        /// </summary>
        [JsonProperty("toEmail")]
        public string ToEmail 
        { 
            get 
            {
                return this.toEmail; 
            } 
            set 
            {
                this.toEmail = value;
                onPropertyChanged("ToEmail");
            }
        }

        /// <summary>
        /// Name of email sender
        /// </summary>
        [JsonProperty("fromName")]
        public string FromName 
        { 
            get 
            {
                return this.fromName; 
            } 
            set 
            {
                this.fromName = value;
                onPropertyChanged("FromName");
            }
        }

        /// <summary>
        /// Email address of email sender
        /// </summary>
        [JsonProperty("fromEmail")]
        public string FromEmail 
        { 
            get 
            {
                return this.fromEmail; 
            } 
            set 
            {
                this.fromEmail = value;
                onPropertyChanged("FromEmail");
            }
        }

        /// <summary>
        /// Date/Time the email was sent
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("timeSent")]
        public DateTime? TimeSent 
        { 
            get 
            {
                return this.timeSent; 
            } 
            set 
            {
                this.timeSent = value;
                onPropertyChanged("TimeSent");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("messageType", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.MessageTypeEnum? MessageType 
        { 
            get 
            {
                return this.messageType; 
            } 
            set 
            {
                this.messageType = value;
                onPropertyChanged("MessageType");
            }
        }

        /// <summary>
        /// Email subject line
        /// </summary>
        [JsonProperty("subject")]
        public string Subject 
        { 
            get 
            {
                return this.subject; 
            } 
            set 
            {
                this.subject = value;
                onPropertyChanged("Subject");
            }
        }

        /// <summary>
        /// Body of the email message
        /// </summary>
        [JsonProperty("body")]
        public string Body 
        { 
            get 
            {
                return this.body; 
            } 
            set 
            {
                this.body = value;
                onPropertyChanged("Body");
            }
        }
    }
} 