/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;

namespace ProNimbusAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum OrderTypeEnum
    {
        CLUB, //TODO: Write general description for this method
        ECOMMERCE, //TODO: Write general description for this method
        RETAIL, //TODO: Write general description for this method
        ENUM_TASTING_ROOM, //TODO: Write general description for this method
        ENUM_NA, //TODO: Write general description for this method
        WEBSITE, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type OrderTypeEnum
    /// </summary>
    public static class OrderTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "Club", "E-Commerce", "Retail", "Tasting Room", "N/A", "Website" };

        /// <summary>
        /// Converts a OrderTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The OrderTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(OrderTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case OrderTypeEnum.CLUB:
                case OrderTypeEnum.ECOMMERCE:
                case OrderTypeEnum.RETAIL:
                case OrderTypeEnum.ENUM_TASTING_ROOM:
                case OrderTypeEnum.ENUM_NA:
                case OrderTypeEnum.WEBSITE:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of OrderTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of OrderTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<OrderTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into OrderTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed OrderTypeEnum value</returns>
        public static OrderTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type OrderTypeEnum", value));

            return (OrderTypeEnum) index;
        }
    }
} 