/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class OrderStatusResponse1 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.StatusEnum? status;
        private Models.Results results;
        private List<Models.GenericError> errors;

        /// <summary>
        /// The status of the call.
        /// * `success` - The system is returning statuses for all orders requested
        /// * `partial` - The system was able to return the status for **some** of the orders requested and not able to return the status for other orders.
        /// * `failure` - The system was able to return the status **none** of the orders requested.
        /// </summary>
        [JsonProperty("status", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.StatusEnum? Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("results")]
        public Models.Results Results 
        { 
            get 
            {
                return this.results; 
            } 
            set 
            {
                this.results = value;
                onPropertyChanged("Results");
            }
        }

        /// <summary>
        /// An array of objects describing what input parameters caused errors.
        /// </summary>
        [JsonProperty("errors")]
        public List<Models.GenericError> Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }
    }
} 