/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class OrderStatusRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string clientCode;
        private Models.DetailViewEnum? detailView;
        private List<string> orderNo;

        /// <summary>
        /// Unique client identifier
        /// </summary>
        [JsonProperty("clientCode")]
        public string ClientCode 
        { 
            get 
            {
                return this.clientCode; 
            } 
            set 
            {
                this.clientCode = value;
                onPropertyChanged("ClientCode");
            }
        }

        /// <summary>
        /// Return extra details in the response, not just the status of the order.
        /// </summary>
        [JsonProperty("detailView")]
        public Models.DetailViewEnum? DetailView 
        { 
            get 
            {
                return this.detailView; 
            } 
            set 
            {
                this.detailView = value;
                onPropertyChanged("DetailView");
            }
        }

        /// <summary>
        /// List of orders
        /// </summary>
        [JsonProperty("orderNo")]
        public List<string> OrderNo 
        { 
            get 
            {
                return this.orderNo; 
            } 
            set 
            {
                this.orderNo = value;
                onPropertyChanged("OrderNo");
            }
        }
    }
} 