/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class ProductDetailsResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private double? code;
        private string message;
        private Dictionary<string, Models.ProductDetailsItem> result;
        private object errors;

        /// <summary>
        /// A numeric representation of the status of the call. Values possible in a successful response are
        ///   * `0` - All products found
        ///   * `2` - Some products not found
        /// </summary>
        [JsonProperty("code")]
        public double? Code 
        { 
            get 
            {
                return this.code; 
            } 
            set 
            {
                this.code = value;
                onPropertyChanged("Code");
            }
        }

        /// <summary>
        /// A string representation of the status of the call. Values possible in a unsuccessful response are
        ///   * All products found
        ///   * Some products not found
        /// </summary>
        [JsonProperty("message")]
        public string Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// An object whose keys are `productSku` values and values are objects as defined in **\<additionalProperties\>**.
        /// </summary>
        [JsonProperty("result")]
        public Dictionary<string, Models.ProductDetailsItem> Result 
        { 
            get 
            {
                return this.result; 
            } 
            set 
            {
                this.result = value;
                onPropertyChanged("Result");
            }
        }

        /// <summary>
        /// An object describing the fields in the request that are in error. May contain multiple levels if the fields in error are part of a field that is an object. If there is no error this object is empty.
        /// </summary>
        [JsonProperty("errors")]
        public object Errors 
        { 
            get 
            {
                return this.errors; 
            } 
            set 
            {
                this.errors = value;
                onPropertyChanged("Errors");
            }
        }
    }
} 