/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;

namespace ProNimbusAPI.Standard.Models
{
    class ProductCreateRequestCreationConverter : JsonCreationConverter<ProductCreateRequest>
    {
        public ProductCreateRequestCreationConverter()
        {
            typeName = "productType";
            dic = new System.Collections.Generic.Dictionary<string, System.Type>()
            {
                { "Merchandise",typeof(Merchandise)},
                { "Wine",typeof(Wine)},
                { "Food",typeof(Food)},
                { "Collateral",typeof(Collateral)},
            };
        }
    }
}