/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class Response : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.RejectedOrder> rejectedOrders;
        private List<Models.AcceptedOrder> acceptedOrders;

        /// <summary>
        /// Array of rejected orders
        /// </summary>
        [JsonProperty("rejectedOrders")]
        public List<Models.RejectedOrder> RejectedOrders 
        { 
            get 
            {
                return this.rejectedOrders; 
            } 
            set 
            {
                this.rejectedOrders = value;
                onPropertyChanged("RejectedOrders");
            }
        }

        /// <summary>
        /// Array of accepted orders
        /// </summary>
        [JsonProperty("acceptedOrders")]
        public List<Models.AcceptedOrder> AcceptedOrders 
        { 
            get 
            {
                return this.acceptedOrders; 
            } 
            set 
            {
                this.acceptedOrders = value;
                onPropertyChanged("AcceptedOrders");
            }
        }
    }
} 