/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class Result1 : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string city;
        private double? distance;
        private string country;
        private string company;
        private Models.Units3Enum? units;
        private string state;
        private string addressLine2;
        private string addressLine1;
        private string postalCode;

        /// <summary>
        /// The city of the address.
        /// </summary>
        [JsonProperty("City")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// The distance from the delivery address in the units specified by the "Units" field.
        /// </summary>
        [JsonProperty("Distance")]
        public double? Distance 
        { 
            get 
            {
                return this.distance; 
            } 
            set 
            {
                this.distance = value;
                onPropertyChanged("Distance");
            }
        }

        /// <summary>
        /// The two-character country code of the address.
        /// </summary>
        [JsonProperty("Country")]
        public string Country 
        { 
            get 
            {
                return this.country; 
            } 
            set 
            {
                this.country = value;
                onPropertyChanged("Country");
            }
        }

        /// <summary>
        /// The company name of the alternate pickup location.
        /// </summary>
        [JsonProperty("Company")]
        public string Company 
        { 
            get 
            {
                return this.company; 
            } 
            set 
            {
                this.company = value;
                onPropertyChanged("Company");
            }
        }

        /// <summary>
        /// Indicates the units for the "Distance" field.
        /// </summary>
        [JsonProperty("Units", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.Units3Enum? Units 
        { 
            get 
            {
                return this.units; 
            } 
            set 
            {
                this.units = value;
                onPropertyChanged("Units");
            }
        }

        /// <summary>
        /// The state code of the address.
        /// </summary>
        [JsonProperty("State")]
        public string State 
        { 
            get 
            {
                return this.state; 
            } 
            set 
            {
                this.state = value;
                onPropertyChanged("State");
            }
        }

        /// <summary>
        /// The optional second line of the address.
        /// </summary>
        [JsonProperty("AddressLine2")]
        public string AddressLine2 
        { 
            get 
            {
                return this.addressLine2; 
            } 
            set 
            {
                this.addressLine2 = value;
                onPropertyChanged("AddressLine2");
            }
        }

        /// <summary>
        /// The required first line of the address.
        /// </summary>
        [JsonProperty("AddressLine1")]
        public string AddressLine1 
        { 
            get 
            {
                return this.addressLine1; 
            } 
            set 
            {
                this.addressLine1 = value;
                onPropertyChanged("AddressLine1");
            }
        }

        /// <summary>
        /// The postal code of the address.
        /// </summary>
        [JsonProperty("PostalCode")]
        public string PostalCode 
        { 
            get 
            {
                return this.postalCode; 
            } 
            set 
            {
                this.postalCode = value;
                onPropertyChanged("PostalCode");
            }
        }
    }
} 