/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class SalesOrderResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.Response response;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("response")]
        public Models.Response Response 
        { 
            get 
            {
                return this.response; 
            } 
            set 
            {
                this.response = value;
                onPropertyChanged("Response");
            }
        }
    }
} 