/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;


namespace ProNimbusAPI.Standard.Models
{
    public class TrackingResponseItem : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string statusCode;
        private string internalTrackingNo;
        private List<Models.TrackingItem> updates;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("statusCode")]
        public string StatusCode 
        { 
            get 
            {
                return this.statusCode; 
            } 
            set 
            {
                this.statusCode = value;
                onPropertyChanged("StatusCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("internalTrackingNo")]
        public string InternalTrackingNo 
        { 
            get 
            {
                return this.internalTrackingNo; 
            } 
            set 
            {
                this.internalTrackingNo = value;
                onPropertyChanged("InternalTrackingNo");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("updates")]
        public List<Models.TrackingItem> Updates 
        { 
            get 
            {
                return this.updates; 
            } 
            set 
            {
                this.updates = value;
                onPropertyChanged("Updates");
            }
        }
    }
} 