/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;

namespace ProNimbusAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum Units3Enum
    {
        MI, //TODO: Write general description for this method
        KM, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type Units3Enum
    /// </summary>
    public static class Units3EnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "MI", "KM" };

        /// <summary>
        /// Converts a Units3Enum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The Units3Enum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(Units3Enum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case Units3Enum.MI:
                case Units3Enum.KM:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of Units3Enum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of Units3Enum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<Units3Enum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into Units3Enum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed Units3Enum value</returns>
        public static Units3Enum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type Units3Enum", value));

            return (Units3Enum) index;
        }
    }
} 