/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;

namespace ProNimbusAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum WineOriginEnum
    {
        ARGENTINA, //TODO: Write general description for this method
        AUSTRALIA, //TODO: Write general description for this method
        AUSTRIA, //TODO: Write general description for this method
        CANADA, //TODO: Write general description for this method
        CHILE, //TODO: Write general description for this method
        CROATIA, //TODO: Write general description for this method
        ENUM_CZECH_REPUBLIC, //TODO: Write general description for this method
        ENGLAND, //TODO: Write general description for this method
        FRANCE, //TODO: Write general description for this method
        GERMANY, //TODO: Write general description for this method
        GREECE, //TODO: Write general description for this method
        HUNGARY, //TODO: Write general description for this method
        INDIA, //TODO: Write general description for this method
        ISRAEL, //TODO: Write general description for this method
        ITALY, //TODO: Write general description for this method
        JAPAN, //TODO: Write general description for this method
        LEBANON, //TODO: Write general description for this method
        LUXEMBOURG, //TODO: Write general description for this method
        MEXICO, //TODO: Write general description for this method
        MOROCCO, //TODO: Write general description for this method
        ENUM_NEW_ZEALAND, //TODO: Write general description for this method
        PORTUGAL, //TODO: Write general description for this method
        ENUM_REPUBLIC_OF_GEORGIA, //TODO: Write general description for this method
        ROMANIA, //TODO: Write general description for this method
        SERBIA, //TODO: Write general description for this method
        SLOVENIA, //TODO: Write general description for this method
        ENUM_SOUTH_AFRICA, //TODO: Write general description for this method
        SPAIN, //TODO: Write general description for this method
        SWITZERLAND, //TODO: Write general description for this method
        TURKEY, //TODO: Write general description for this method
        ENUM_UNITED_STATES, //TODO: Write general description for this method
        URUGUAY, //TODO: Write general description for this method
        UNKNOWN, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type WineOriginEnum
    /// </summary>
    public static class WineOriginEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "Argentina", "Australia", "Austria", "Canada", "Chile", "Croatia", "Czech Republic", "England", "France", "Germany", "Greece", "Hungary", "India", "Israel", "Italy", "Japan", "Lebanon", "Luxembourg", "Mexico", "Morocco", "New Zealand", "Portugal", "Republic of Georgia", "Romania", "Serbia", "Slovenia", "South Africa", "Spain", "Switzerland", "Turkey", "United States", "Uruguay", "Unknown" };

        /// <summary>
        /// Converts a WineOriginEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The WineOriginEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(WineOriginEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case WineOriginEnum.ARGENTINA:
                case WineOriginEnum.AUSTRALIA:
                case WineOriginEnum.AUSTRIA:
                case WineOriginEnum.CANADA:
                case WineOriginEnum.CHILE:
                case WineOriginEnum.CROATIA:
                case WineOriginEnum.ENUM_CZECH_REPUBLIC:
                case WineOriginEnum.ENGLAND:
                case WineOriginEnum.FRANCE:
                case WineOriginEnum.GERMANY:
                case WineOriginEnum.GREECE:
                case WineOriginEnum.HUNGARY:
                case WineOriginEnum.INDIA:
                case WineOriginEnum.ISRAEL:
                case WineOriginEnum.ITALY:
                case WineOriginEnum.JAPAN:
                case WineOriginEnum.LEBANON:
                case WineOriginEnum.LUXEMBOURG:
                case WineOriginEnum.MEXICO:
                case WineOriginEnum.MOROCCO:
                case WineOriginEnum.ENUM_NEW_ZEALAND:
                case WineOriginEnum.PORTUGAL:
                case WineOriginEnum.ENUM_REPUBLIC_OF_GEORGIA:
                case WineOriginEnum.ROMANIA:
                case WineOriginEnum.SERBIA:
                case WineOriginEnum.SLOVENIA:
                case WineOriginEnum.ENUM_SOUTH_AFRICA:
                case WineOriginEnum.SPAIN:
                case WineOriginEnum.SWITZERLAND:
                case WineOriginEnum.TURKEY:
                case WineOriginEnum.ENUM_UNITED_STATES:
                case WineOriginEnum.URUGUAY:
                case WineOriginEnum.UNKNOWN:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of WineOriginEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of WineOriginEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<WineOriginEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into WineOriginEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed WineOriginEnum value</returns>
        public static WineOriginEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type WineOriginEnum", value));

            return (WineOriginEnum) index;
        }
    }
} 