/*
 * ProNimbusAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ProNimbusAPI.Standard;
using ProNimbusAPI.Standard.Utilities;

namespace ProNimbusAPI.Standard.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum WineTypeEnum
    {
        ENUM_STILL_WINE, //TODO: Write general description for this method
        NONALCOHOLIC, //TODO: Write general description for this method
        ENUM_SPARKLING_WINE, //TODO: Write general description for this method
        ENUM_FORTIFIED_WINE, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type WineTypeEnum
    /// </summary>
    public static class WineTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "Still Wine", "Non-Alcoholic", "Sparkling Wine", "Fortified Wine" };

        /// <summary>
        /// Converts a WineTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The WineTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(WineTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case WineTypeEnum.ENUM_STILL_WINE:
                case WineTypeEnum.NONALCOHOLIC:
                case WineTypeEnum.ENUM_SPARKLING_WINE:
                case WineTypeEnum.ENUM_FORTIFIED_WINE:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of WineTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of WineTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<WineTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into WineTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed WineTypeEnum value</returns>
        public static WineTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type WineTypeEnum", value));

            return (WineTypeEnum) index;
        }
    }
} 