/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const APIException = require('./APIException');
/**
 * Creates an instance of OrderStatusResponse1ErrorException
 */
class OrderStatusResponse1ErrorException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * The status of the call.
         * * `success` - The system is returning statuses for all orders requested
         * * `partial` - The system was able to return the status for **some** of the orders requested
         * and not able to return the status for other orders.
         * * `failure` - The system was able to return the status **none** of the orders requested.
         */
        this.status = null;

        /**
         * TODO: Write general description for this field
         */
        this.results = null;

        /**
         * An array of objects describing what input parameters caused errors.
         */
        this.errors = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'status', realName: 'status' },
            { name: 'results', realName: 'results', type: 'Results' },
            { name: 'errors', realName: 'errors', array: true, type: 'GenericError' },
        ]);
    }
}

module.exports = OrderStatusResponse1ErrorException;
