/**
 * ProNimbusAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const APIException = require('./APIException');
/**
 * Creates an instance of ProductUpdateResponseFailureException
 */
class ProductUpdateResponseFailureException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * The status of the call.
         * * `failure` - The system was not able to update the SKU
         * * `success` - The system updated the SKU successfully
         */
        this.status = null;

        /**
         * TODO: Write general description for this field
         */
        this.results = null;

        /**
         * An array of objects describing what input parameters caused errors.
         */
        this.errors = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'status', realName: 'status' },
            { name: 'results', realName: 'results', type: 'Results1' },
            { name: 'errors', realName: 'errors', array: true, type: 'GenericError' },
        ]);
    }
}

module.exports = ProductUpdateResponseFailureException;
